### ISSUE TITLE
PyInstaller로 만든 exe파일이 안돌아요!

### ISSUE THREAD

**Issue by minhoryang** [JinQlambert/Project#1]
Jupyter Notebook에서 ipynb를 바로 py로 빼면 get_ipython()함수가 생기는데 이게 .exe로 실행을 방해합니다.

1. py로 파일을 뺀 다음 get_ipython()라인을 주석처리하던지
2. 어차피 pyInstaller가 exe를 만들어줄 때 우리가 사용하는 파일을 골라서 넣어주니까
```!pip install``` 줄은 뺍시다.

**Comment by JinQlambert** [comment]
:)
