### ISSUE TITLE
새로운 에러가 발견되었어요

### ISSUE THREAD

**Issue by JinQlambert** [JinQlambert/Project#14]
![default](https://user-images.githubusercontent.com/23021639/34966041-2489daa6-fa9c-11e7-812f-726e12c63763.JPG)
어떤문제일까요???

찾아보고있어요

**Comment by JinQlambert** [comment]
WinError 10061을 찾아보니 제가 IF문에 driver.quit()을 넣었던 것이 문제였던거 같아요
https://stackoverflow.com/questions/46159539/web-scraping-with-python-and-selenium-no-connection-could-be-made-because-the-t
루프에 걸렸다나 뭐라나...
지금 github에는 아직 quit이 있는 파일로 올려놨어용 한번 체크해주세요

**Comment by minhoryang** [comment]
그 사이에 webdriver가 죽었다는데요?!?!?!?
언제 driver.quit()을 넣었대요? ;ㅅ;

**Comment by minhoryang** [comment]
아 그렇네요;;;; driver.quit()을 없애야해요;ㅅ;...
그리고 코드가 꽤 바뀌어서 test가 pass하지 않을 수도 있겠네요.

**Comment by JinQlambert** [comment]
그럼일단 테스트를 다시 돌려볼게요

**Comment by minhoryang** [comment]
해결?

**Comment by JinQlambert** [comment]
해결!
