### ISSUE TITLE
로그인 테스트 필요

### ISSUE THREAD

**Issue by JinQlambert** [JinQlambert/Project#4]
1. 로그인 테스트가 필요(어떻게?)

2. 비밀번호 변경, 불일치 등의 팝업 또는 이슈에 대해 대처 필요

**Comment by minhoryang** [comment]
테스트를 위해 해당 페이지(로그인/그 이후)의 목업파일저장이 필요.

**Comment by minhoryang** [comment]
해당하는 페이지들을 Ctrl+S로 저장해서 따로 저에게 보내주세요.

**Comment by minhoryang** [comment]
너가 보내준 파일을 그대로 쓰면 되겠다. :)

**Comment by minhoryang** [comment]
이건 너가 #13 끝내면 내가 해줄게!

**Comment by minhoryang** [comment]
`pip install pytest`
한 다음
`python test.py` 돌려봐

**Comment by minhoryang** [comment]
테스트가 잘 수행됨을 확인하였습니다.
