### ISSUE TITLE
간단한 리뷰를 해보았어요.

### ISSUE THREAD

**Issue by minhoryang** [JinQlambert/Project#5]
b865c7e16a649d2f939bb9a9d2b72c3db85c11c8 를 참고해주세요!
다 답변을 하시고 절 @minhoryang 으로 불러주시면되요.

**Comment by JinQlambert** [comment]
@minhoryang 일단 생각나는대로 답변을 달았어요!

**Comment by minhoryang** [comment]
오 다 좋아요!
