### ISSUE TITLE
방금 위험한 정보를 지웠어요.

### ISSUE THREAD

**Issue by minhoryang** [JinQlambert/Project#6]
31eb2ce307b64f7dcb9dec26072cd10321cba184 에서 확인해보세요.

**Comment by minhoryang** [comment]
https://github.com/JinQlambert/Project/commit/9f5a371d836008362ac0915bac69e3846f45a4a9#diff-47a034d806662974a1df3b8818530d36R74 여기도 있어요!

**Comment by JinQlambert** [comment]
고마워요!
