### ISSUE TITLE
Browser에서 뜨는 Alert를 어떻게 처리해야할까?

### ISSUE THREAD

**Issue by JinQlambert** [JinQlambert/Project#7]
![default](https://user-images.githubusercontent.com/23021639/34545028-552310b0-f12d-11e7-9bed-9a14d5d645e7.jpg)

위와같은 에러메시지 출력.

문제점 진단

1. 먼저 input()으로 정의한 변수 loginID와 loginpw를 RealEvent에서 읽지 못한다
이는 @minhoryang 형이 말한것처럼 같은 함수내에서 정의된 것이 아니면 메모리가 날아가버린것으로 판단된다.

2. 에러가 계속 지속 
process_metrics.cc(105) 에러 : 구글링 결과 다른 사람들도 비슷한 에러를 겪고 있으며 나같은 경우에는 프로그램 구동 실패과정에서 발생, 다른 사람들은 프로그램 구동 성공이후에도 위와같은 에러로 나온듯 싶다.
Chrome Driver GitHub의 질문창에서 위와같은 내용을 확인할 수 있는데 결과적으로 구버전의 크롬드라이버를 실행할 경우에는 이상이 없는것으로 봐선 크롬드라이버 자체의 문제라고 봐도 될 듯 하다.

3. 셀레니움이 알아서 새로운 경고(팝업)을 인식한다 이 부분을 이용해서 로그인 에러를 파악할 수 있을까? 이를 슬랙이나 다른곳으로 알림을 보낼 수 있을까?

해결방안 - 앞으로의 진행점
1. 먼저 input()으로 정의한 변수 loginID와 loginpw의 위치 지정(민호량의 지적)후 다시 테스트

2. 로그인 에러시 능동적으로 해결 가능하거나 결과를 받아볼수 있는 방법이 필요함

3.

**Comment by minhoryang** [comment]
엌 2번에러는 뭐야! ㅠ_ㅠ process_metrics.cc 알아볼게

**Comment by minhoryang** [comment]
아 설마. alert가 뜰 것 같으면 이를 미리 try-except로 잡을 수 있는 것 같은데?
alert창이 뜨는동안은 chrome에 커서를 둘 수 없으니까 조정을 못하고 process_metrics.cc가 뜨는것같은느낌?

**Comment by minhoryang** [comment]
[뜰 것 같은 Alert를 처리하는 방법!](https://stackoverflow.com/a/19019311)

**Comment by minhoryang** [comment]
[먼저 input()으로 정의한 변수 loginID와 loginpw를 RealEvent에서 읽지 못한다](https://github.com/JinQlambert/Project/blob/master/20180104ForTest.py#L48-L49)
여기보니까 변수가 아니라 string으로 지정되어있네! 이거 수정하면되겠다!
```python
driver.find_element_by_name('USER_ID').send_keys('loginid')
driver.find_element_by_name('PASSWD').send_keys('loginpw')
```
to
```python
driver.find_element_by_name('USER_ID').send_keys(loginid)
driver.find_element_by_name('PASSWD').send_keys(loginpw)
```
