### ISSUE TITLE
베타를 내어보았어용

### ISSUE THREAD

**Issue by JinQlambert** [JinQlambert/Project#8]
(왜 링크가 안걸릴까요....;;;;;)
@minhoryang 

일단 먼저 TEST가 필요해요

1. 예측가능한 alert를 처리하는 것은 그대로 긁어와서 수정이 필요할것같아요

2.  slack 봇 토큰이 그대로 노출되어있어요

3. ID와 pw를 글로벌 변수로 처리했어요

4. 현재까지는 로그인,->출근->출근 확인 페이지로 되었는데 버튼이 안눌리고 넘어가는 경우는 없을까요?

5. bs4, slaker 등등이 많이 추가되어서 프로그램이 느려지는게 아닐까 걱정되어요

6. 만약 출근 시간 전까지 오류를 해결할 수 없으면 어떻게 해야할까요?(팀뷰어로 수동으로 해야하나)
  
7. 슬랙봇을 통해 보낼 텍스트(bs4)가 공백이 너무많아서 해결할 방법을 고민중이에요(한줄당 td로 묶여있어서)

**Comment by minhoryang** [comment]
ㅇㅎㅇㅎㅇㅎ
너가 걱정하던부분이 다 맞게 걱정한것같아. 이만하면 충분하다!

**Comment by minhoryang** [comment]
기능은 추가하지 말고 이걸 이제 조여볼까?

**Comment by minhoryang** [comment]
이렇게 파일과 함수를 나눠보는건 어때?
- main.py
  - 아래의 함수를 차례대로 다 부른다.
  - schedule은 여기에 있음.
- login.py
  - login_prompt()  =>  (id, pw)를 리턴한다.
  - login(chrome, id, pw) 로그인을 시도한다.
- attendance.py
  - attendance(chrome)
- slack.py
  - send(slack_api_key, message)

**Comment by JinQlambert** [comment]
![error 1](https://user-images.githubusercontent.com/23021639/34809049-e0537550-f6d5-11e7-80ae-0bf0da4010f2.JPG)
![error 2](https://user-images.githubusercontent.com/23021639/34809050-e26fcdf2-f6d5-11e7-8308-726aaaa4abbc.JPG)

지금 일어나는 에러들이에요

먼제 from attendance import Attendance 해도 에러가 나고

import attendance로 하면 에러가 안나더라구영
해당 모듈 호출은 되었는데

안에서 정의된 Attendance는 어떻게 해도 찾을 수가 없네용

**Comment by JinQlambert** [comment]
![error 3](https://user-images.githubusercontent.com/23021639/34809077-298064e0-f6d6-11e7-9cf6-f0a0f0ae4800.JPG)

요러케 나와용!

**Comment by minhoryang** [comment]
에? Attendance라는 함수가 없는거 아닐까?

**Comment by minhoryang** [comment]
> 예측가능한 alert를 처리하는 것은 그대로 긁어와서 수정이 필요할것같아요

-> #7 

> slack 봇 토큰이 그대로 노출되어있어요

-> #10

> ID와 pw를 글로벌 변수로 처리했어요

-> 이건 파일을 나누면서 해결했지요?

> 현재까지는 로그인,->출근->출근 확인 페이지로 되었는데 버튼이 안눌리고 넘어가는 경우는 없을까요?

-> 이건 알아봐야겠어요. #11

> bs4, slaker 등등이 많이 추가되어서 프로그램이 느려지는게 아닐까 걱정되어요

-> 괜찮아요. 오버워치처럼 3D도 안들어갔는데 ^^

> 만약 출근 시간 전까지 오류를 해결할 수 없으면 어떻게 해야할까요?(팀뷰어로 수동으로 해야하나)

-> 이건 수동으로 해야겠지요.... 그러니 확신이 생길때까지는 일찍 출근하는게^^

> 슬랙봇을 통해 보낼 텍스트(bs4)가 공백이 너무많아서 해결할 방법을 고민중이에요(한줄당 td로 묶여있어서)

-> 텍스트를 예쁘게 만들어야겠네요! #12
