### ISSUE TITLE
Mission) 파일을 분리해 봅시다!

### ISSUE THREAD

**Issue by JinQlambert** [JinQlambert/Project#9]
https://github.com/JinQlambert/Project/commit/1efd0816f4470b22fdaebacd476cef5df06af468

입니당
@minhoryang 
아직 slack을 어떤 타이밍에 진행되게 할 수 있을지 고민이 끝나지 않았어요.

attendance의 schedule 두 줄이 제대로 진행될지 걱정이에요

def 한 두 줄이 저기서 돌아갈까요?

**Comment by minhoryang** [comment]
해당 커밋에 코멘트 남겼어요! 잘했어요!!!!

**Comment by minhoryang** [comment]
코멘트에 나온 것들 적용하고 닫아주세요.
- import 빠진 것, 빼도될 것
- loginID/loginpw/driver 넘겨주는 것
